title : Life is a chunky pattern
tagline: %w{Ruby Javascript SoftwareDesign}.blogify
author :
  name : Gabriel Dehan
  email : dehan dot gabriel at gmail dot com
  github : gabriel-dehan
  twitter : GabrielDehan
  feedburner : feedname

navigation :
  - readings.md
  - archive.html
  - tags.html
  - categories.html

  
